version: '3'
services:
  client:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/src
    command: bash -c "yarn && yarn dev"
    tty: true
    ports:
      - 8080:8080